INITIAL_PLAYER_HEALS: int = 3
SCORE_SUCCESS_ATTACK: int = 1
SCORE_ENEMY_DOWN: int = 5
INITIAL_ENEMY_LEVEL: int = 1

KNIGHT = 1
THIEF = 2
WIZARD = 3
SUCCESSFUL_ATTACKS = ((KNIGHT, THIEF), (THIEF, WIZARD), (WIZARD, KNIGHT))
VALID_CHOICES = KNIGHT, THIEF, WIZARD

SUCCESSFUL_ATTACK = "YOUR ATTACK IS SUCCESSFUL!"
FAILED_ATTACK = "YOUR ATTACK IS FAILED!"
DRAW = "IT'S A DRAW!"
SUCCESSFUL_DEFENCE = "YOUR DEFENCE IS SUCCESSFUL!"
FAILED_DEFENCE = "YOUR DEFENCE IS FAILED!"
